DEFAULT_MULTIPLIER=100
DEFAULT_DELIMITER='-'

GATEWAY_DEPLOYMENT_SLEEP_SECONDS=1
GATEWAY_DEPLOYMENT_UPDATE_DELAY_SECONDS=600

LAMBDA_SLEEP_SECONDS=5
LAMBDA_UPDATE_TIME_OUT_SECONDS=600

DEFAULT_TAG='latest'